stages:
  - angular-build

build:
  stage: angular-build
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" # only for push develop
    #- if: $CI_COMMIT_TAG # only for tag
  image: docker:1.11
  services:
    - docker:dind
  script:
    - if [ "$CI_BUILD_TAG" == "" ]; then IMG_TAG="$CI_COMMIT_REF_SLUG"; else IMG_TAG="$CI_BUILD_TAG"; fi
    - docker build -t $CI_REGISTRY_IMAGE:develop .
    - docker tag $CI_REGISTRY_IMAGE:develop $CI_REGISTRY_IMAGE:$IMG_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$IMG_TAG
